export const accountTripConstants = {
  LOAD: 'tripConstants/LOAD',
  LOAD_SUCCESS: 'tripConstants/LOAD_SUCCESS',
  LOAD_FAIL: 'tripConstants/LOAD_FAIL',
  FLUSH: 'tripConstants/FLUSH',
  ALL_TRIP_ACCOUNTS: 'tripConstants/ALL_TRIP_ACCOUNTS',
  ALL_TRIP_LEG_ID: 'tripConstants/ALL_TRIP_LEG_ID',
  ALL_CORPORATE_ACCOUNT: 'tripConstants/ALL_CORPORATE_ACCOUNT',
  SAVE_TRIP_ACCOUNTS: 'tripConstants/SAVE_TRIP_ACCOUNTS',
  DELETE_TRIP_ACCOUNTS: 'tripConstants/DELETE_TRIP_ACCOUNTS',
  ALL_COMPLETED_TRIPS: 'tripConstants/ALL_COMPLETED_TRIPS',
  GET_QUOTE: 'tripConstants/GET_QUOTE',
  GET_QUOTE_SUCCESS: 'tripConstants/GET_QUOTE_SUCCESS',
  GET_QUOTE_FAIL: 'tripConstants/GET_QUOTE_FAIL',
  SAVE_QUOTATION: 'tripConstants/SAVE_QUOTATION',
  FLUSH_QUOTATION: 'tripConstants/FLUSH_QUOTATION',
  SAVE_LEG: 'tripConstants/SAVE_LEG',
  SAVE_FILTERS: 'tripConstants/SAVE_FILTERS',
  GET_FILTERS: 'tripConstants/GET_FILTERS',
};
